### ISSUE TITLE
Jacobi induced distribution error

### ISSUE THREAD

**Issue by akilnarayan** [SCIInstitute/UncertainSCI#14]
```
import numpy as np
from families import JacobiPolynomials

alpha = -0.95703125
beta = -0.8710937500000002

J = JacobiPolynomials(alpha=alpha,beta=beta)

print(J.idist(-1, 0)) # Should be 0
```

Outputs [0.11839635] instead of 0.

This also causes issues downstream when inverting these distributions. (Does the matlab code work for this case?)

**Comment by ZEXINLIU** [comment]
I got 0 correctly. It's weird.

**Comment by ZEXINLIU** [comment]
I just fixed this. Just wondering how should I link my commit to this issue to show that it's been solved?

**Comment by dcwhite** [comment]
The keyword and number need to be adjacent, like "fixes #14: Jacobi..."

**Comment by dcwhite** [comment]
https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords

**Comment by ZEXINLIU** [comment]
Thanks, Dan. I changed my commit to Closes#14: Jacobi.... But it seems this issue is still open.

**Comment by dcwhite** [comment]
Changing it after the fact and force-pushing is not the best practice--we should protect master and require pull requests, then issues can be closed by merging the pull requests if the commit messages don't line up exactly. That's how other repos manage access.

**Comment by ZEXINLIU** [comment]
Okay, I got it. I will do this as you suggested next time. Thanks a lot.
