### ISSUE TITLE
Expose parameter samples before model evaluation

### ISSUE THREAD

**Issue by akilnarayan** [SCIInstitute/UncertainSCI#30]

**Comment by jab0707** [comment]
It would be nice if the results of model evaluation could be also provided back to UncertainSCI all at once. 
so pull out the parameter samples, then run them all and provide back all of the answer all at once. This would allow for parallel solving of the model for all of the parameter selections

**Comment by akilnarayan** [comment]
This is a feature that should be fixed in a current branch undergoing review. You could wait until its merged into `master`, or it's on the `discrete-chebyshev` branch in `demos/pce_build.py`.
