### ISSUE TITLE
setup file does not set the correct environment libraries

### ISSUE THREAD

**Issue by jcollfont** [SCIInstitute/UncertainSCI#83]
I am having issues installing the UncertainSCI package in my environment and running the demo examples.

After following the installation instructions in the documentation the UncrertainSCI package does not get installed in the environment.
To clarify, I ran the "pip install ."  command without any errors being reported.
Afterwards, I tried running a demo script and ipython throws error when trying to load the packages:

      3 from scipy import sparse as sprs
      4  ##
----> 5 from UncertainSCI.families import JacobiPolynomials, HermitePolynomials, LaguerrePolynomials
      6 from UncertainSCI.families import DiscreteChebyshevPolynomials
      7 from UncertainSCI.opolynd import TensorialPolynomials

ModuleNotFoundError: No module named 'UncertainSCI'

I tried to install the software on two computers (mac and ubuntu), bith with python 3.8 installed

Any idea what could be the issue?

Thanks for your help!
Jaume

**Comment by jcollfont** [comment]
Issue solved.

**Comment by jessdtate** [comment]
#96
