### ISSUE TITLE
Update documentation for setup.py

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/UncertainSCI#84]
Issue solved.

The documentation is incorrect. The 'setup.py' file needs to be run from the root folder of the UncertainSCI tree. In the documentation it currently reads as it should be run from the UncertainSCI folder within the installation

_Originally posted by @jcollfont in https://github.com/SCIInstitute/UncertainSCI/issues/83#issuecomment-870603841_

**Comment by jessdtate** [comment]
#96
