### ISSUE TITLE
Feature Request: Access PCE sample weights

### ISSUE THREAD

**Issue by jab0707** [SCIInstitute/UncertainSCI#86]
I would like to be able to access the weights of the PCE samples that are used to make the emulator. Something like:
``` python
samples = pce.samples
weights = pce.weights
assert len(samples) == len(weights), "There should be one weight per sample"
```

**Comment by akilnarayan** [comment]
See #88. There are now two new methods:
- `PolynomialChaosExpansion.training_weights`, which returns sample weights used in training. This might not give what you expect (e.g., the weights won't sum to 1)
- `PolynomialChaosExpansion.integration_weights`, which returns weights more akin to weights for a biased ensemble. The weights will sum to 1, but some weights might be negative.

I am not sure which of the above you want/need. We can talk about it if the above isn't clear.
