### ISSUE TITLE
Feature Request: Expose running of the pce emulator after it is built

### ISSUE THREAD

**Issue by jab0707** [SCIInstitute/UncertainSCI#87]
I would like an easy way to run the PCE emulator once it has been created on any arbitrary new sample Iw ould like to examine. Something like this:
``` python
#For some modelFunction with three input parameters
pce.build()
newSample = np.array([0,5,2])
emulatorOutput = pce.emulator.sample(newSample)
modelOutput = modleFunction(newSample)
compareOutputs(emulatorOutput, modelOutput)
```

**Comment by akilnarayan** [comment]
The `pce_eval` method of `PolynomialChaosExpansion` allows you to do this. (It's also now aliased as `eval`.) See #88, and also line 47 of `demos/simple_boxplots.py`
